### PR TITLE
Clear up settings

### PR DESCRIPTION
**Pull request by wesleybl**
Remove old stuff from product settings.

### CODE REVIEW

**Review by Arhell — APPROVED** [review]

**Review by ale-rt — CHANGES_REQUESTED** [review]
This looks really good :)
Thanks!
It would be great to have an upgrade step that:
- creates the proper registry records if missing
- moves the configuration from the annotations to the registry if the registry is unconfigured
- removes the old annotations

Also that `TRY_REGISTRY` should be cleaned up: the package is declared to work only on Plone 5.2, where the registry is always present.

**Comment by wesleybl** [comment]
> Also that TRY_REGISTRY should be cleaned up: the package is declared to work only on Plone 5.2, where the registry is always present.

This looks to me like an integration with the `plone.formwidget.recaptcha` product. To see:

https://github.com/collective/collective.recaptcha/blob/cfb2db9070ff652678624fafb22847930b3f1a39/src/collective/recaptcha/settings.py#L30

I wanted to keep this integration. Perhaps the name of the constant should be changed?

**Comment by wesleybl** [comment]
> - moves the configuration from the annotations to the registry if the registry is unconfigured
> - removes the old annotations

I delete the class from the annotation:

https://github.com/collective/collective.recaptcha/pull/25/files#diff-1796e3d755aa16dca04040d049b1f8cd0724527d2ddfeb4326967798a7da212fL44-L52

How to access data in this situation?

**Comment by wesleybl** [comment]
@ale-rt any tips here? At some point we will break this. Maybe we'll implement an upgrade that no one will use. These annotations seem to be quite old.

**Comment by ale-rt** [comment]
You could restore the class or add an alias see https://github.com/plone/plone.app.upgrade/blob/94fc3c66b2840f57479036547c0176f15bf9b0df/plone/app/upgrade/__init__.py#L25

**Comment by wesleybl** [comment]
@ale-rt  Well, inserting an alias is one more thing we will have to remove in the future. So I prefer to restore the class.

But imagine the situation:

- we released release 3.0.0 with class and with step upgrade.
- then we release release 4.0.0 without the class.
- whoever used the class and upgraded from a version < 3.0.0 to 4.0.0 will have the problem.
- most likely, it will migrate keys "by hand", before discovering it had an upgrade step in version 3.0.0.

Do you still think it's worth the upgrade step?

**Review by mauritsvanrees — APPROVED** [review]
This package reads the settings from the registry since PR #2, which is in version 1.1.5 from 2014. Ideally, an upgrade step would have been written at that time.
I am very much in favour of having a proper upgrade path, but it seems too late to write one now.

**Comment by mauritsvanrees** [comment]
About `TRY_REGISTRY`:

> I wanted to keep this integration. Perhaps the name of the constant should be changed?

This was introduced in commit 826c7e7e5729072c718b552a11aa1fd2e8b5a11d. Its intention was for integration with `plone.formwidget.recaptcha`. The name of the constant is strange now. I suggest renaming it to `TRY_FORMWIDGET`.

**Comment by wesleybl** [comment]
> The name of the constant is strange now. I suggest renaming it to TRY_FORMWIDGET.

Done: https://github.com/collective/collective.recaptcha/pull/25/commits/e4ecd8e9dec47b9c29e69ee20145fed1f8133be9

**Comment by mauritsvanrees** [comment]
`black` fails. Is probably fixed when you merge master into this branch, or rebase.

**Comment by mauritsvanrees** [comment]
@ale-rt Are you okay with merging now, without upgrade step?
See also [my comment about it](#pullrequestreview-909443789).

**Review by ale-rt — APPROVED** [review]
LGTM

**Pull request merged**
