### PR TITLE
Use Github Actions for CI

### PR DESCRIPTION
**Pull request by wesleybl**
- Black
- isort
- lint
- codecov

### CODE REVIEW

**Review by mauritsvanrees — APPROVED** [review]
Thanks. That seems about right.

**Comment by wesleybl** [comment]
@mauritsvanrees You can please click the `Create new webhook` button at:

https://app.codecov.io/gh/collective/collective.recaptcha/settings

I don't have permission to click on it because I'm not an admin for this repository. I think it's for `codecov` make the coverage comments in PRs.

**Comment by frapell** [comment]
I tried to do it but got this 
image

Never configured codecov, so not sure what that means

**Comment by wesleybl** [comment]
@frapell I also get this message when clicking the button. I was guessing it was because I'm not `collective.recaptha` admin. Are you an administrator?

**Comment by frapell** [comment]
Ahhh, no, I'm not

**Comment by mauritsvanrees** [comment]
But I am! :-D
I have recreated the web hook.

**Pull request merged**
